# 1) A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two unitsA randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.



In [36]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import norm

In [37]:
Cutlets = pd.read_csv("Cutlets.csv")

In [38]:
Cutlets.head()

Unit_A  Unit_B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [39]:
Cutlets.shape

(35, 2)

In [41]:
Cutlets.describe()

Unit_A     Unit_B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [42]:
UnitA = pd. Series(Cutlets.iloc[:,0])
UnitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit_A, dtype: float64

In [43]:
UnitB = pd.Series(Cutlets.iloc[:,1])
UnitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit_B, dtype: float64

In [44]:
#2_sample 2_tail ttest
t_stat,p_value = stats.ttest_ind(UnitA,UnitB)
p_value

0.4722394724599501

In [45]:
print("T_statistic:{1} P_value:{0}".format(t_stat,p_value))

T_statistic:0.4722394724599501 P_value:0.7228688704678063


In [46]:
# compare p_value with α = 0.05
if p_value < 0.05:
    print("We reject null hypothesis")
else:
    print("we accept null hypothesis")

we accept null hypothesis


# 2) A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
LabTAT.mtw

In [47]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import norm

In [48]:
LabTat = pd.read_csv("LabTAT.csv")

In [49]:
LabTat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [50]:
LabTat.shape

(120, 4)

In [51]:
LabTat.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [52]:
#(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(LabTat.iloc[:,0],LabTat.iloc[:,1],LabTat.iloc[:,2],LabTat.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [53]:
# compare it with α = 0.05
p_value[1]

2.1156708949992414e-57

# 3) Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [54]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [55]:
buyerratio = pd.read_csv("BuyerRatio.csv")

In [56]:
buyerratio.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [57]:
buyerratio.shape

(2, 5)

In [58]:
buyerratio.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [13]:
#dimensional array
x=np.array([[50,142,131,70],[435,1523,1356,750]])
x

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [17]:
# Chi2 contengency independence test
p_value=chi2_contingency(x)
p_value

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [18]:
p_value[1]

0.6603094907091882

In [19]:
if p_value[1] < 0.05:
    print("It reject null hypothesis")
else:
    print("It will accept null hypothesis")

It will accept null hypothesis


# 4) TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Minitab File: CustomerOrderForm.mtw
 

In [20]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [21]:
CustomerOrderForm = pd.read_csv("Costomer+OrderForm.csv")

In [22]:
CustomerOrderForm.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [23]:
CustomerOrderForm.shape

(300, 4)

In [24]:
CustomerOrderForm.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [26]:
CustomerOrderForm.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [27]:
CustomerOrderForm.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [29]:
CustomerOrderForm.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [30]:
CustomerOrderForm.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [31]:
y=np.array([[271,267,269,280],[29,33,31,20]])
y

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [33]:
# Chi2 contengency independence test
p_value=chi2_contingency(y) 
p_value

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [34]:
p_value[1]

0.2771020991233135

In [35]:
if p_value[1] < 0.05:
    print("We reject null hypothesis")
else:
    print("We accept null hypothesis")

We accept null hypothesis
